// <auto-generated />
namespace CenturyAirlines.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateflights19 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateflights19));
        
        string IMigrationMetadata.Id
        {
            get { return "201905051113146_update-flights19"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
